definitions:
  entity.EntityCloudAccount:
    properties:
      access_key_id:
        type: string
      active:
        type: boolean
      cloud_provider:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      nickname:
        type: string
      secret_access_key:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/cloud_account/cloud_account:
    get:
      consumes:
      - application/json
      description: Get all cloud accounts
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/entity.EntityCloudAccount'
      security:
      - ApiKeyAuth: []
      summary: Get all cloud accounts
      tags:
      - CloudAccount
swagger: "2.0"
