// Code generated by MockGen. DO NOT EDIT.
// Source: app/usecase/instance (interfaces: IUseCaseInstance)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "app/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIUseCaseInstance is a mock of IUseCaseInstance interface.
type MockIUseCaseInstance struct {
	ctrl     *gomock.Controller
	recorder *MockIUseCaseInstanceMockRecorder
}

// MockIUseCaseInstanceMockRecorder is the mock recorder for MockIUseCaseInstance.
type MockIUseCaseInstanceMockRecorder struct {
	mock *MockIUseCaseInstance
}

// NewMockIUseCaseInstance creates a new mock instance.
func NewMockIUseCaseInstance(ctrl *gomock.Controller) *MockIUseCaseInstance {
	mock := &MockIUseCaseInstance{ctrl: ctrl}
	mock.recorder = &MockIUseCaseInstanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUseCaseInstance) EXPECT() *MockIUseCaseInstanceMockRecorder {
	return m.recorder
}

// ActiveDeactiveInstance mocks base method.
func (m *MockIUseCaseInstance) ActiveDeactiveInstance(arg0 int64, arg1 bool) (*entity.EntityInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveDeactiveInstance", arg0, arg1)
	ret0, _ := ret[0].(*entity.EntityInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveDeactiveInstance indicates an expected call of ActiveDeactiveInstance.
func (mr *MockIUseCaseInstanceMockRecorder) ActiveDeactiveInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveDeactiveInstance", reflect.TypeOf((*MockIUseCaseInstance)(nil).ActiveDeactiveInstance), arg0, arg1)
}

// CreateInstance mocks base method.
func (m *MockIUseCaseInstance) CreateInstance(arg0 *entity.EntityInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockIUseCaseInstanceMockRecorder) CreateInstance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockIUseCaseInstance)(nil).CreateInstance), arg0)
}

// CreateOrUpdateInstance mocks base method.
func (m *MockIUseCaseInstance) CreateOrUpdateInstance(arg0 *entity.EntityInstance, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateInstance", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateInstance indicates an expected call of CreateOrUpdateInstance.
func (mr *MockIUseCaseInstanceMockRecorder) CreateOrUpdateInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateInstance", reflect.TypeOf((*MockIUseCaseInstance)(nil).CreateOrUpdateInstance), arg0, arg1)
}

// DeleteInstance mocks base method.
func (m *MockIUseCaseInstance) DeleteInstance(arg0 *entity.EntityInstance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockIUseCaseInstanceMockRecorder) DeleteInstance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockIUseCaseInstance)(nil).DeleteInstance), arg0)
}

// GetAll mocks base method.
func (m *MockIUseCaseInstance) GetAll(arg0 entity.SearchEntityInstanceParams) ([]entity.EntityInstance, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]entity.EntityInstance)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIUseCaseInstanceMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIUseCaseInstance)(nil).GetAll), arg0)
}

// GetAllOFCalendar mocks base method.
func (m *MockIUseCaseInstance) GetAllOFCalendar(arg0 int) ([]entity.EntityInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOFCalendar", arg0)
	ret0, _ := ret[0].([]entity.EntityInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOFCalendar indicates an expected call of GetAllOFCalendar.
func (mr *MockIUseCaseInstanceMockRecorder) GetAllOFCalendar(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOFCalendar", reflect.TypeOf((*MockIUseCaseInstance)(nil).GetAllOFCalendar), arg0)
}

// GetByID mocks base method.
func (m *MockIUseCaseInstance) GetByID(arg0 int64) (*entity.EntityInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0)
	ret0, _ := ret[0].(*entity.EntityInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIUseCaseInstanceMockRecorder) GetByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIUseCaseInstance)(nil).GetByID), arg0)
}

// GetByInstanceID mocks base method.
func (m *MockIUseCaseInstance) GetByInstanceID(arg0 string) (*entity.EntityInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInstanceID", arg0)
	ret0, _ := ret[0].(*entity.EntityInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInstanceID indicates an expected call of GetByInstanceID.
func (mr *MockIUseCaseInstanceMockRecorder) GetByInstanceID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInstanceID", reflect.TypeOf((*MockIUseCaseInstance)(nil).GetByInstanceID), arg0)
}

// UpdateInstance mocks base method.
func (m *MockIUseCaseInstance) UpdateInstance(arg0 *entity.EntityInstance, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstance", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstance indicates an expected call of UpdateInstance.
func (mr *MockIUseCaseInstanceMockRecorder) UpdateInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstance", reflect.TypeOf((*MockIUseCaseInstance)(nil).UpdateInstance), arg0, arg1)
}
