// Code generated by MockGen. DO NOT EDIT.
// Source: app/usecase/calendar (interfaces: IRepositoryCalendar)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "app/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRepositoryCalendar is a mock of IRepositoryCalendar interface.
type MockIRepositoryCalendar struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryCalendarMockRecorder
}

// MockIRepositoryCalendarMockRecorder is the mock recorder for MockIRepositoryCalendar.
type MockIRepositoryCalendarMockRecorder struct {
	mock *MockIRepositoryCalendar
}

// NewMockIRepositoryCalendar creates a new mock instance.
func NewMockIRepositoryCalendar(ctrl *gomock.Controller) *MockIRepositoryCalendar {
	mock := &MockIRepositoryCalendar{ctrl: ctrl}
	mock.recorder = &MockIRepositoryCalendarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepositoryCalendar) EXPECT() *MockIRepositoryCalendarMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIRepositoryCalendar) Create(arg0 *entity.EntityCalendar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIRepositoryCalendarMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIRepositoryCalendar)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockIRepositoryCalendar) Delete(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIRepositoryCalendarMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIRepositoryCalendar)(nil).Delete), arg0)
}

// GetAll mocks base method.
func (m *MockIRepositoryCalendar) GetAll(arg0 entity.SearchEntityCalendarParams) ([]entity.EntityCalendar, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]entity.EntityCalendar)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIRepositoryCalendarMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIRepositoryCalendar)(nil).GetAll), arg0)
}

// GetFromID mocks base method.
func (m *MockIRepositoryCalendar) GetFromID(arg0 int) (*entity.EntityCalendar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromID", arg0)
	ret0, _ := ret[0].(*entity.EntityCalendar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromID indicates an expected call of GetFromID.
func (mr *MockIRepositoryCalendarMockRecorder) GetFromID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromID", reflect.TypeOf((*MockIRepositoryCalendar)(nil).GetFromID), arg0)
}

// Update mocks base method.
func (m *MockIRepositoryCalendar) Update(arg0 *entity.EntityCalendar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIRepositoryCalendarMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIRepositoryCalendar)(nil).Update), arg0)
}
