// Code generated by MockGen. DO NOT EDIT.
// Source: app/usecase/log (interfaces: IUsecaseLog)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "app/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIUsecaseLog is a mock of IUsecaseLog interface.
type MockIUsecaseLog struct {
	ctrl     *gomock.Controller
	recorder *MockIUsecaseLogMockRecorder
}

// MockIUsecaseLogMockRecorder is the mock recorder for MockIUsecaseLog.
type MockIUsecaseLogMockRecorder struct {
	mock *MockIUsecaseLog
}

// NewMockIUsecaseLog creates a new mock instance.
func NewMockIUsecaseLog(ctrl *gomock.Controller) *MockIUsecaseLog {
	mock := &MockIUsecaseLog{ctrl: ctrl}
	mock.recorder = &MockIUsecaseLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsecaseLog) EXPECT() *MockIUsecaseLogMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIUsecaseLog) Create(arg0 *entity.EntityLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIUsecaseLogMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUsecaseLog)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockIUsecaseLog) Delete(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIUsecaseLogMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIUsecaseLog)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockIUsecaseLog) Get(arg0 int) (*entity.EntityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*entity.EntityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIUsecaseLogMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIUsecaseLog)(nil).Get), arg0)
}

// GetAll mocks base method.
func (m *MockIUsecaseLog) GetAll(arg0 entity.SearchEntityLogParams) ([]entity.EntityLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]entity.EntityLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIUsecaseLogMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIUsecaseLog)(nil).GetAll), arg0)
}

// Update mocks base method.
func (m *MockIUsecaseLog) Update(arg0 *entity.EntityLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIUsecaseLogMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUsecaseLog)(nil).Update), arg0)
}
