// Code generated by MockGen. DO NOT EDIT.
// Source: app/usecase/log (interfaces: IRepositoryLog)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "app/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRepositoryLog is a mock of IRepositoryLog interface.
type MockIRepositoryLog struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryLogMockRecorder
}

// MockIRepositoryLogMockRecorder is the mock recorder for MockIRepositoryLog.
type MockIRepositoryLogMockRecorder struct {
	mock *MockIRepositoryLog
}

// NewMockIRepositoryLog creates a new mock instance.
func NewMockIRepositoryLog(ctrl *gomock.Controller) *MockIRepositoryLog {
	mock := &MockIRepositoryLog{ctrl: ctrl}
	mock.recorder = &MockIRepositoryLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepositoryLog) EXPECT() *MockIRepositoryLogMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIRepositoryLog) Create(arg0 *entity.EntityLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIRepositoryLogMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIRepositoryLog)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockIRepositoryLog) Delete(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIRepositoryLogMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIRepositoryLog)(nil).Delete), arg0)
}

// GetAll mocks base method.
func (m *MockIRepositoryLog) GetAll(arg0 entity.SearchEntityLogParams) ([]entity.EntityLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]entity.EntityLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIRepositoryLogMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIRepositoryLog)(nil).GetAll), arg0)
}

// GetFromID mocks base method.
func (m *MockIRepositoryLog) GetFromID(arg0 int) (*entity.EntityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromID", arg0)
	ret0, _ := ret[0].(*entity.EntityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromID indicates an expected call of GetFromID.
func (mr *MockIRepositoryLogMockRecorder) GetFromID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromID", reflect.TypeOf((*MockIRepositoryLog)(nil).GetFromID), arg0)
}

// Update mocks base method.
func (m *MockIRepositoryLog) Update(arg0 *entity.EntityLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIRepositoryLogMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIRepositoryLog)(nil).Update), arg0)
}
